### ISSUE TITLE
linkage error for opengl lib

### ISSUE THREAD

**Issue by mediabuff** [martinrotter/qt-minimalistic-builds#16]
Thanks the pre-built static libraries. I got most my externals resolved except the following. How was the source compiled for static ? with what opengl flags ?

I am using https://github.com/martinrotter/qt-minimalistic-builds/releases/download/5.15.2/qt-5.15.2-static-msvc2019-x86_64.7z in MSVC2019

`1>Qt5Guid.lib(qopenglpaintengine.obj) : error LNK2019: unresolved external symbol __imp_glLoadIdentity referenced in function "public: virtual void __cdecl QOpenGL2PaintEngineEx::beginNativePainting(void)" (?beginNativePainting@QOpenGL2PaintEngineEx@@UEAAXXZ)

1>Qt5Guid.lib(qopenglpaintengine.obj) : error LNK2019: unresolved external symbol __imp_glLoadMatrixf referenced in function "public: virtual void __cdecl QOpenGL2PaintEngineEx::beginNativePainting(void)" (?beginNativePainting@QOpenGL2PaintEngineEx@@UEAAXXZ)

1>Qt5Guid.lib(qopenglpaintengine.obj) : error LNK2019: unresolved external symbol __imp_glMatrixMode referenced in function "public: virtual void __cdecl QOpenGL2PaintEngineEx::beginNativePainting(void)" (?beginNativePainting@QOpenGL2PaintEngineEx@@UEAAXXZ)

1>Qt5Guid.lib(qopenglpaintengine.obj) : error LNK2019: unresolved external symbol __imp_glOrtho referenced in function "public: virtual void __cdecl QOpenGL2PaintEngineEx::beginNativePainting(void)" (?beginNativePainting@QOpenGL2PaintEngineEx@@UEAAXXZ)

`

**Comment by mediabuff** [comment]
Added 'opengl32.lib'. Did'nt help.

**Comment by mediabuff** [comment]
Qt has the above reqferences between lines 689-719.

https://github.com/qt/qtbase/blob/d79a9b1a4f694a227ce62ccab9b44685a9755916/src/opengl/qopenglpaintengine.cpp

**Comment by martinrotter** [comment]
Hello @mediabuff could you please prepare [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_working_example) and upload for me so that I could test?

**Comment by mediabuff** [comment]
In the process of creating a minimal app, the linkage error vanished in the small app. Don't know why. But now I get runtime error. Attached sample program.
`
'qml_test.exe' (Win32): Loaded 'D:\MyDevProjects\MyTempProjects\temp\qml_test\x64\Debug\qml_test.exe'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\D3D12.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\D3DCompiler_47.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\dcomp.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\dwmapi.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Symbols loaded.
'qml_test.exe' (Win32): Unloaded 'C:\Windows\System32\gdi32.dll'
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\wtsapi32.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Symbols loaded.
'qml_test.exe' (Win32): Unloaded 'C:\Windows\System32\msvcrt.dll'
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\d3d11.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\opengl32.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\IPHLPAPI.DLL'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\userenv.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\netapi32.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\glu32.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'D:\MyDevProjects\MyTempProjects\temp\qml_test\x64\Debug\libcrypto-1_1-x64.dll'. 
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140d.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140_1d.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140_1d.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140d.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbased.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\netutils.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\srvcli.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\wldp.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\umpdc.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\clbcatq.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\AppXDeploymentClient.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\c0316479.inf_amd64_909fbb4582f4a5b4\atig6pxx.dll'. 
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\c0316479.inf_amd64_909fbb4582f4a5b4\atio6axx.dll'. 
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\dxva2.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\atig6txx.dll'. 
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\atiadlxx.dll'. 
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\psapi.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\propsys.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'. Symbols loaded.
'qml_test.exe' (Win32): Loaded 'C:\Windows\System32\DXCore.dll'. Symbols loaded.
qrc:/example_item.qml:3:1: module "QtQuick.Controls" is not installed 
     import QtQuick.Controls 2.2
 
     ^
qrc:/example_item.qml:1:1: module "QtQuick" is not installed 
     import QtQuick 2.3
 
     ^
qrc:/example_item.qml:3:1: module "QtQuick.Controls" is not installed 
     import QtQuick.Controls 2.2
 
     ^
qrc:/example_item.qml:1:1: module "QtQuick" is not installed 
     import QtQuick 2.3
 
     ^
Exception thrown: read access violation.
**item** was nullptr.

The program '[39500] qml_test.exe' has exited with code 0 (0x0).
[qml_test.vcxproj.zip](https://github.com/martinrotter/qt-minimalistic-builds/files/6078457/qml_test.vcxproj.zip)

`

**Comment by martinrotter** [comment]
not sure how to solve, check new qt 6 builds
