### ISSUE TITLE
Cannot add to vs2019 via qt-vs-addin 2.7.1

### ISSUE THREAD

**Issue by hcaihao** [martinrotter/qt-minimalistic-builds#18]
![image](https://user-images.githubusercontent.com/3926845/130596774-ddb562a9-2d08-4463-8406-591d48a95ac8.png)

---------------------------
Microsoft Visual Studio
---------------------------
Qt VS Tools

Invalid Qt versions:

 * Path does not exist
---------------------------
确定   
---------------------------

**Comment by martinrotter** [comment]
I do not use that addin sorry. Perhaps it is something with Qt "relocatable" feature, which is turned on in that build.

**Comment by hcaihao** [comment]
Do you use `nmake install` after build?
