### ISSUE TITLE
Plans to support Qt 5.15-kde

### ISSUE THREAD

**Issue by JulienMaille** [martinrotter/qt-minimalistic-builds#19]
I was looking at a way to incorporate kde's LGPL patches on top of latest Qt5.15.2 opensource.
I started modifying your script and noticed a bit too late that `https://invent.kde.org/qt/qt/qtbase/-/tree/kde/5.15` is only covering qtbase, and each subpackage would have to be downloaded and extracted one by one.
Have you considered this feature? Would you have any guidance how to do this in a clean way?
thanks

**Comment by martinrotter** [comment]
Well, that's certainly interesting as their 5.15.2+ code will have some backported fixes/stuff si will be probably more stable than upstream.

Also, one thing. I plan to regularly compile 6.2+ once it comes out, but at this point there are still some build bugs which I reproted to Qt guys.

**Comment by JulienMaille** [comment]
@martinrotter I'm bringing this up once again. Currently trying to compile it on my side with a modified ps script.
I took inspiration from https://github.com/mxe/mxe/issues/2685

```sh
#!/bin/bash

# Script to build a Qt 5.15 LST from KDE compilation patches repository.
#
# Copyright (c) 2015-2021 by Gilles Caulier  <caulier dot gilles at gmail dot com>
#
# Redistribution and use is allowed according to the terms of the BSD license.
# For details see the accompanying COPYING-CMAKE-SCRIPTS file.
#

set -e
set -C

git clone --progress --verbose --branch kde/5.15 --single-branch https://invent.kde.org/qt/qt/qt5.git kde-5.15-LTS
cd kde-5.15-LTS

git submodule update --init --recursive --progress

# Remove Qt6 sub-modules

rm -rf                  \
    qtcanvas3d          \
    qtdocgallery        \
    qtfeedback          \
    qtpim               \
    qtqa                \
    qtrepotools         \
    qtsystems

# Switch sub-modules to kde/5.15 branches

QT_SUBDIRS=$(ls -F | grep / | grep qt)

echo "Git module sub-directories to switch to kde/5.15 branch: $QT_SUBDIRS"

for SUBDIR in $QT_SUBDIRS ; do

    echo "Branching $SUBDIR to kde/5.15..."
    cd $SUBDIR
    git checkout kde/5.15 || true
    cd ..

done
exit
# Remove .git sub directories

GIT_SUBDIRS=$(find  . -name '.git')

echo "Git internal sub-directories to remove: $GIT_SUBDIRS"

for SUBDIR in $GIT_SUBDIRS ; do

    echo "Removing $SUBDIR..."
    rm -fr $SUBDIR

done
```

**Comment by JulienMaille** [comment]
Testing something like this
```powershell
$version_kde = "5.15.kde"
$arch = $Env:Platform

$qt_sources_url = "https://invent.kde.org/qt/qt/qt5.git"
$qt_src_base_folder = $pwd.Path + "\qt-everywhere-src-" + $version_kde

# Clone Qt sources
git clone --progress --verbose --branch kde/5.15 --single-branch $qt_sources_url $qt_src_base_folder
cd $qt_src_base_folder

# Remove Qt6 sub-modules
rm -r -fo qtcanvas3d, qtdocgallery, qtfeedback, qtpim, qtqa, qtrepotools, qtsystems

# Switch sub-modules to kde/5.15 branch
git submodule foreach git checkout kde/5.15
```

**Comment by martinrotter** [comment]
And you want to compile that for windows right?

**Comment by JulienMaille** [comment]
Yes windows for my use case, why? It did compile just fine.

**Comment by martinrotter** [comment]
I see, ok. Should I compile as well?

**Comment by JulienMaille** [comment]
Well I think it would make sense to have a dedicated powershell in your collection. This is supposed to result in the "best Qt5 build available" ie. the most recent one + backported fixes from Qt6. What do you think?

**Comment by martinrotter** [comment]
Yes that is my thinking too.

**Comment by martinrotter** [comment]
BTW.  i updated to msvc 2022 and qt build fails for me RN, will test in coming days what is wrong

**Comment by JulienMaille** [comment]
What kind of error message did you get?
