### ISSUE TITLE
mix /MT and /MD CXXFLAGS in 15.5.2-static ?

### ISSUE THREAD

**Issue by dafanasiev** [martinrotter/qt-minimalistic-builds#20]
The installation says to use /MT (multithread, **static version** of the run-time library):
https://github.com/martinrotter/qt-minimalistic-builds/blob/ea43a53c0f06681df92c5bc1bb4d35a261f0a84b/msvc2019-build5.15.2-static.ps1#L18-L25

but qt build (you can see that result depends on vc runtime dlls) with `/MD` (Causes the application to use the multithread-specific and **DLL-specific version** of the run-time library).

* `-static-runtime` option should be passed to `configure` if you need `/MT` build 
* or build openssl with `/MD`.

Bug?

howtocheck:
1. `lib /list  Qt5Widgets.lib`
2. take one obj and extract: `lib /extract:.obj\release\qaction.obj /out:qaction.obj Qt5Widgets.lib`
3. see raw bytes in `qaction.obj` (or use sysinternals `strings` tool):
```
 -compiler:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\c2.dll"    
-typedil -f C:\qtb\qt-everywhere-src-5.15.2\qtbase\src\widgets\kernel\qaction.cpp
 -dos -Fdvc140.pdb -GS -Yu -FitObjFunc -FitObjData -ThrowingNew 
-MD
-Og -Os -Ob2 -Gy -pdbrpc -W 3 -Fo
```

**Comment by martinrotter** [comment]
will address issue for qt 6
