### ISSUE TITLE
QT_PLUGIN_PATH needs setting

### ISSUE THREAD

**Issue by mennodeij** [martinrotter/qt-minimalistic-builds#22]
I installed qt-5.12.9-dynamic-msvc2019-x86_64 from the 7zip archive. 
During builds I noticed that the qhelpgenerator.exe - which is used during the build - gave an error message box (actually, my whole screen was full of them for each project that failed to start the utility 😉). Running it from the commandline gives the following error:
```
qt.qpa.plugin: Could not find the Qt platform plugin "minimal" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
This could be fixed by setting the environment variable `QT_PLUGIN_PATH` to `<install-location>\plugins`.
Maybe this can be documented for future users that may encounter the same issue.

**Comment by martinrotter** [comment]
I see. It would interest me, how "official" builds do this.

**Comment by martinrotter** [comment]
Does it help if you drop the variable and copy this file: https://github.com/martinrotter/qt-minimalistic-builds/blob/master/qt.conf into root of Qt?

**Comment by mennodeij** [comment]
A copy of qt.conf in the `bin` folder works as well, yes. I can't comment on how 'official' builds do this, for that I don't have experience with these official builds I'm afraid.

**Comment by martinrotter** [comment]
Yes. The "qt.conf" way is likely "official" one as it is there to provide "relocatable" qt builds.
