### ISSUE TITLE
Add Qt 6.3

### ISSUE THREAD

**Issue by Detector-I** [martinrotter/qt-minimalistic-builds#23]
Hi, thank you for your perfect work, your work really helped me a lot.
Can you please add static version of Qt 6.3? there is some very good feature that I would love to test them like the new Qml compiler, and bunch more.

at the end I have some other question that I will be happy if you answer them

- I tried to use your Qt 6.2.2 static version in VS2019 with Qt plugin, but dont know why it can detect it sadly, do you have any Idea what is the problem?
- other thing, currently your static build out size is very good I mean I can get my compiled output at around <10MB, you think this is possible to get the file size to be smaller?

again thank you for your works

**Comment by martinrotter** [comment]
Yes, there is missing file.

Download [this](https://github.com/martinrotter/qt-minimalistic-builds/releases/download/6.2.2-static/qt.conf) and copy it into `bin` folder of Qt-6.2.2-static.

As for Qt 6.3.0. It is not released yet.

https://wiki.qt.io/Qt_6.3_Release

**Comment by martinrotter** [comment]
> * other thing, currently your static build out size is very good I mean I can get my compiled output at around <10MB, you think this is possible to get the file size to be smaller?

Possibly not. I enabled `/LTCG` which is probably the biggest deal when it comes to small static libs/binaries. I cannot think of some other ways to make it even smaller.

**Comment by Detector-I** [comment]
> Yes, there is missing file.
> 
> Download [this](https://github.com/martinrotter/qt-minimalistic-builds/releases/download/6.2.2-static/qt.conf) and copy it into `bin` folder of Qt-6.2.2-static.
> 
> Also, the build is not `relocatable` which is my fault, but should work with the file above. Will be fixed for my 6.3.0 build.

thank you, with adding this file I finally managed to add the **Qt6.2.2** to my VS2019
but now it give me `cannot open input file 'zlib.lib'` error in compile... do I need to link zlib manually?

> > * other thing, currently your static build out size is very good I mean I can get my compiled output at around <10MB, you think this is possible to get the file size to be smaller?
> 
> Possibly not. I enabled `/LTCG` which is probably the biggest deal when it comes to small static libs/binaries. I cannot think of some other ways to make it even smaller.

Ok thank you, by itself the output file size is very good right now...

**Comment by martinrotter** [comment]
> but now it give me `cannot open input file 'zlib.lib'` error in compile... do I need to link zlib manually?

That is weird. `zlib.lib` should be placed in `lib` subdirectory of your Qt-static. Link against it manually as I guess it might be needed in some cases.

**Comment by Detector-I** [comment]
> > but now it give me `cannot open input file 'zlib.lib'` error in compile... do I need to link zlib manually?
> 
> That is weird. `zlib.lib` should be placed in `lib` subdirectory of your Qt-static. Link against it manually as I guess it might be needed in some cases.

yeah you where right. it was actually there, but for some weird reason it wasn't included the compiler couldn't find it...
by adding path to lib folder to `Additional Library Directories` in VS2019 property page it fixed...
don't know why it didn't added it by default.

**Comment by martinrotter** [comment]
Hard to say, I do not use VS2019 with Qt, I use Qt creator (but think about switch to VS code maybe).
