### ISSUE TITLE
5.15.3  dynamic cannot build

### ISSUE THREAD

**Issue by zx950921** [martinrotter/qt-minimalistic-builds#27]
i get qt-5.15.3-dynamic-msvc2019-x86_64,
qtcreator put out  error: LNK1104: cannot open file “**\qt-5.15.3-dynamic-msvc2019-x86_64\lib.obj”

What parameters need to be configured?

**Comment by martinrotter** [comment]
try to create file "qt.conf" inside "bin" directory and place this inside:

```
[Paths]
Prefix = ..
```

**Comment by zx950921** [comment]
> try to create file "qt.conf" inside "bin" directory and place this inside:
> 
> ```
> [Paths]
> Prefix = ..
> ```

i do it but still have this error

**Comment by martinrotter** [comment]
dont know, sry

**Comment by shatyuka** [comment]
I also encountered this problem. A directory has been provided to link.
<img src='https://user-images.githubusercontent.com/31368738/162609767-5ac06964-3cd5-486f-a7a8-8eaf2c5b29bf.png' width='50%'>
