### ISSUE TITLE
More Details on Step 3

### ISSUE THREAD

**Issue by CycloneRing** [martinrotter/qt-minimalistic-builds#28]
Hi there, Great Repo!
Can you add some detail on how to add static versions to qt creator?
I mean 
> Setup your Qt Creator to use new libraries.

I added qmake to versions but it gives warnings and doesn't work, It says : 
> qt version is not properly installed please run make install

**Comment by martinrotter** [comment]
Copy file qt.conf (see below for download) into bin directory of extracted Qt. I forget to package it!

https://github.com/martinrotter/qt-minimalistic-builds/releases/download/5.15.3/qt.conf

**Comment by CycloneRing** [comment]
I'm talking about 6.2.2 static
