### ISSUE TITLE
Qt 5.15.5 builds

### ISSUE THREAD

**Issue by nejatafshar** [martinrotter/qt-minimalistic-builds#31]
Qt 5.15.5 has been open sourced. It would be great if the builds are added.

**Comment by JulienMaille** [comment]
@martinrotter are you able to properly compile qslmysql plugin with latest 5.15.5/6 ?
I'm getting `ERROR: Feature 'sql-mysql' was enabled, but the pre-condition 'libs.mysql' failed` error when running configure

**Comment by martinrotter** [comment]
building qt 5.15.11
